[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = 'DataPump'
version = '0.1.0'
description = "An Data Dump project that processes CSV files."
readme = 'README.md'
requires-python = ">=3.11"
license = "MIT"

dependencies = [
    'fastapi[standard]',
    'uvicorn[standard]',
    'pydantic',
    'psycopg',
    'psycopg-pool',
]

[tool.setuptools.packages.find]
include = ['DataPump']